"""physics - 物理學模組（相對論、電磁學、量子力學、控制理論等）。"""

from .relativity import (
    lorentz_factor,
    lorentz_transformation,
    time_dilation,
    length_contraction,
    relativistic_momentum,
    relativistic_energy,
    mass_energy_equivalence,
    spacetime_interval,
    schwarzschild_metric,
    friedmann_metric,
)
from .electromagnetism import (
    coulomb_law,
    electric_field_point_charge,
    magnetic_field_wire,
    biot_savart_law,
    ampere_law_line,
    faraday_law,
    maxwell_equations_check,
    poynting_vector,
)
from .quantum import (
    planck_constant,
    de_broglie_wavelength,
    wave_function_free_particle,
    probability_density,
    heisenberg_uncertainty_check,
    tunneling_probability,
    particle_in_box_wave_function,
    energy_levels_particle_in_box,
    spin_state_representation,
    pauli_matrices,
)
from .control import (
    transfer_function,
    routh_hurwitz,
    controllability_matrix,
)

__all__ = [
    "lorentz_factor",
    "lorentz_transformation",
    "time_dilation",
    "length_contraction",
    "relativistic_momentum",
    "relativistic_energy",
    "mass_energy_equivalence",
    "spacetime_interval",
    "schwarzschild_metric",
    "friedmann_metric",
    "coulomb_law",
    "electric_field_point_charge",
    "magnetic_field_wire",
    "biot_savart_law",
    "ampere_law",
    "faraday_law",
    "maxwell_equations_check",
    "poynting_vector",
    "planck_constant",
    "de_broglie_wavelength",
    "wave_function_free_particle",
    "probability_density",
    "heisenberg_uncertainty_check",
    "tunneling_probability",
    "particle_in_box_wave_function",
    "energy_levels_particle_in_box",
    "spin_state_representation",
    "pauli_matrices",
    "transfer_function",
    "step_response",
    "pid_controller",
    "routh_hurwitz",
    "state_space",
    "controllability_matrix",
    "is_controllable",
    "observability_matrix",
    "is_observable",
]
