"""math4py - A Python library for mathematics."""

from . import statistics as R
from .geometry import Point, Vector
from .geometry._3d import Line3D, Plane3D
from .plot import (
    boxplot,
    brownian_motion,
    hist,
    ito_integral_plot,
    options_plot,
    plot,
    plot_entropy,
    plot_kl,
    qqnorm,
)
from .statistics import (
    anova,
    chisq_test,
    conf_interval,
    correlation as cor,
    covariance as cov,
    cross_entropy,
    dbinom,
    dchisq,
    df,
    dnorm,
    dpois,
    dt,
    entropy,
    kl_divergence,
    mean,
    median,
    mutual_information,
    pbinom,
    pchisq,
    pf,
    pnorm,
    ppois,
    pt,
    qbinom,
    qchisq,
    qf,
    qnorm,
    qpois,
    qt,
    quantile,
    rbinom,
    rchisq,
    rf,
    rnorm,
    rpois,
    rt,
    std as sd,
    summary,
    t_test,
    variance as var,
    z_test,
)

__all__ = [
    "Vector",
    "Point",
    "Line3D",
    "Plane3D",
    "R",
    "det",
    "dnorm",
    "pnorm",
    "qnorm",
    "rnorm",
    "dt",
    "pt",
    "qt",
    "rt",
    "dchisq",
    "pchisq",
    "qchisq",
    "rchisq",
    "df",
    "pf",
    "qf",
    "rf",
    "dbinom",
    "pbinom",
    "qbinom",
    "rbinom",
    "dpois",
    "ppois",
    "qpois",
    "rpois",
    "mean",
    "median",
    "var",
    "sd",
    "cov",
    "cor",
    "quantile",
    "summary",
    "t_test",
    "z_test",
    "chisq_test",
    "anova",
    "conf_interval",
    "entropy",
    "cross_entropy",
    "kl_divergence",
    "mutual_information",
    "plot",
    "hist",
    "boxplot",
    "qqnorm",
    "plot_entropy",
    "plot_kl",
    "brownian_motion",
    "ito_integral_plot",
    "options_plot",
]
__version__ = "0.1.0"
