"""calculus - 微積分模組，數值微積分 (符號用 sympy 直接用)."""

from .analysis import (
    cauchy_sequence,
    extreme_value_theorem,
    intermediate_value_theorem,
    is_continuous,
    limit,
    mean_value_theorem,
    pointwise_convergence,
    sequence_limit,
    uniform_convergence,
)
from .function import derivative, integral, simpson, trapezoidal
from .measure import (
    counting_measure,
    dirac_measure,
    is_lebesgue_measurable,
    is_measure,
    lebesgue_integral_simple,
    lebesgue_measure_1d,
    lebesgue_measure_2d,
    measure_space_check,
    outer_measure_1d,
    sigma_algebra_generated,
)
from .series import (
    alternating_harmonic_series,
    fourier_series,
    geometric_series,
    harmonic_series,
    power_series,
    ratio_test,
    root_test,
    series_convergence,
    taylor_series,
)

__all__ = [
    "derivative",
    "integral",
    "trapezoidal",
    "simpson",
    "taylor_series",
    "fourier_series",
    "power_series",
    "geometric_series",
    "harmonic_series",
    "alternating_harmonic_series",
    "ratio_test",
    "root_test",
    "series_convergence",
    "limit",
    "is_continuous",
    "pointwise_convergence",
    "uniform_convergence",
    "intermediate_value_theorem",
    "mean_value_theorem",
    "extreme_value_theorem",
    "sequence_limit",
    "cauchy_sequence",
    "is_measure",
    "lebesgue_measure_1d",
    "lebesgue_measure_2d",
    "is_lebesgue_measurable",
    "outer_measure_1d",
    "counting_measure",
    "dirac_measure",
    "sigma_algebra_generated",
    "measure_space_check",
    "lebesgue_integral_simple",
]
